### ISSUE TITLE
レジストリが読めないうえにエラーがおかしい - This can't read registry key and the funny error is obtained

### ISSUE THREAD

**Issue by Kamioda** [AinoMegumi/Windows_Registry_Reader#1]
RegOpenKeyEx関数の戻り値が2となっているため、読み込めていないことが分かる。
しかし、GetLastError関数でエラーを取得すると、エラーコード0のメッセージを返してくる。

The return value of "RegOpenKeyEx" function is 2, so it can be that this doesn't read registry key.
But after getting error by "GetLastError" function, it returns the message of error code 0.

**Comment by yumetodo** [comment]
エラーメッセージが狂っている件は治っていないが、開けない問題は

#2 #3 で修正した

**Comment by Kamioda** [comment]
でも取得した値は間違っている

But the getting num is wrong.

**Comment by yumetodo** [comment]
@AinoMegumi pullreqしました ( #4 )

**Comment by Kamioda** [comment]
pullreq確認しました

I checked the pull request.
